#import "conf.typ": *

#show: bamboo-theme.with(
	title: "Stern-Gerlach Experiment", 
	author: "Luca Cicu - Lorenzo Liuzzo", 
	date: "27/11/2025",
)

#title-slide()

= Experiment description
== Apparatus
#align(
	horizon, 
	figure(
		image("assets/apparatus.png", width: 70%)
	)
)

== Angular & Magnetic momenta
#slide[
	#figure(
		image("assets/angular_magnetic_momentum.png", width: 65%),
		caption: figure.caption(
			position: bottom, 
			[*Angular* and *magnetic* momenta generated by an electron orbiting circularly.]
		)
	)
][
	#pause
	*Angular momentum*
	$ bold(L) = bold(x) times bold(p) $

	#pause
	#v(10pt)		
	*Magnetic momentum*
	$ bold(mu) = I Sigma hat(bold(n)) $
	#v(5pt)
	#pause
	$ bold(mu) = (q v) / (2 pi r) pi r^2 hat(bold(n)) = q/(2m) bold(L) quad => quad bold(mu) prop bold(L) $

	#pause
	#v(10pt)
	=== *Magnetic Hamiltonian*
	#v(5pt)
	$ H_(text("magn")) = - bold(mu) dot bold(B) $
]


== Magnetic Interaction
#slide[
	#figure(
		image("assets/force.png", width: 80%),
		caption: [Microscopic origin of the magnetic force.],
		gap: 20pt
	)
][
	#align(horizon, [

		$ bold(F) = - nabla H_(text("magn")) = nabla(bold(mu) dot bold(B)) $
		
		#pause
		$ F_z = mu_z (partial B_z)/(partial z) #pause = m dot.double(z) $

		$ z(t) = z_0 + dot(z)_0 t + mu_z/(2 m) (partial B_z)/(partial z) t^2 $
	])
]


== Classical Prediction
#align(horizon + center, figure(image("assets/predicted.png", width: 40%)))

== Observed Results
#align(horizon + center, figure(image("assets/observed.png", width: 38%)))

#focus-slide[=== Why two deflected spots?]

= Historical Context
== Historical Context
#slide[
	#pause
	#align(center, image("assets/Max_Planck_Nobel.jpg"))
][
	#pause
	#align(center, image("assets/Albert_Einstein_Nobel.jpg"))
][
	#pause
	#align(center, image("assets/Niels_Bohr_Nobel.jpg"))
]


= Quantum Mechanics

== QM --- States in Hilbert Space
#slide[
	$ |psi chevron.r in HH $

	#pause
	- *Basis Properties*
	$ chevron.l e_i|e_j chevron.r = delta_(i j) quad quad I = sum_i |e_i chevron.r chevron.l e_i| $

	#pause
	- *Superposition Principle* 
	$ |psi chevron.r = sum_i |e_i chevron.r chevron.l e_i|psi chevron.r = sum_i c_i^psi|e_i chevron.r $
	$c_i^psi = chevron.l e_i|psi chevron.r$ are *probability amplitudes* 
][
	#pause
	#v(40pt)
	- *Inner product* 
	$ chevron.l phi|psi chevron.r = sum_i chevron.l phi|e_i chevron.r chevron.l e_i|psi chevron.r = sum_i (c_i^phi)^* c_i^psi $

	#pause
	- *Born's rule* 
	$ chevron.l psi|psi chevron.r = sum_i (c_i^psi)^* c_i^psi = sum_i |c_i^psi|^2 = 1 $
	$|c_i^psi|^2$ is the *probability* to find $|psi chevron.r$ in $|e_i chevron.r$
]



== QM --- Operators
#v(10pt)
A *linear operator* $hat(O)$ is a transformation from an Hilbert space into itself, that acts like
$ hat(O)(alpha|psi chevron.r + beta|phi chevron.r) = alpha hat(O)|psi chevron.r + beta hat(O)|phi chevron.r = alpha|psi' chevron.r + beta|phi' chevron.r $ 

#v(30pt)
#pause
The action of $hat(O)$ on a state can be entirely represented by its action on some *basis*: 
$ |psi' chevron.r = hat(O)|psi chevron.r = sum_i hat(O)|e_i chevron.r chevron.l e_i|psi chevron.r = sum_(i j) |e_j chevron.r chevron.l e_j|hat(O)|e_i chevron.r chevron.l e_i|psi chevron.r = sum_(i j) |e_j chevron.r O_(i j) c_i^psi $ 

#v(20pt)
#pause
We can also define the *adjoint* operator $hat(O)^dagger$: $quad chevron.l psi'| = chevron.l psi|hat(O)^dagger quad hat(O)^dagger_(i j) = (hat(O)_(j i))^*$



== QM --- Operators & Observables
We can associate every *observable* of a system to an operator
$ 
	hat(O) = sum_i lambda_i|e_i chevron.r chevron.l e_i| 
	quad quad
	hat(O)|e_j chevron.r = sum_i lambda_i|e_i chevron.r chevron.l e_i|e_j chevron.r = lambda_j|e_j chevron.r 
$
#pause
where $lambda_i$ are the *possible results* and $|e_i chevron.r$ are the *possible states* in which the system can be founded *after* the measurement. 
#v(10pt)
#pause
The requirements are that, *independently by the choice of the basis*,  
$ chevron.l e_i|e_j chevron.r = delta_(i j) quad quad lambda_i^* = lambda_i $  

#pause
#v(10pt)
Such operators are called *hermitian* and satisfy 
$quad hat(O)^dagger_(i j) = lambda_i^* delta_(i j) = lambda_i delta_(i j) = hat(O)_(i j)$



== QM --- Commutator of Operators
#v(10pt)
We define the *commutator* between two operators $hat(A)$ and $hat(B)$ as
$ [hat(A), hat(B)] = hat(A) hat(B) - hat(B) hat(A) = - [hat(B), hat(A)] $

#pause
#v(20pt)
$hat(A), hat(B)$ are said to be *compatible iif they commute*, so that $[hat(A), hat(B)] = 0$. 

#pause
#v(30pt)
Two observables can be *simultaneously* determined iif their operators are compatible, \
that is if they share a *common basis* of eigenstates:
$ 
	hat(A)|e_i chevron.r = lambda_i|e_i chevron.r quad 
	hat(B)|e_i chevron.r = mu_i|e_i chevron.r quad <=> quad 
	chevron.l e_i|[hat(A), hat(B)]|e_j chevron.r = (lambda_i mu_i - lambda_j mu_j) chevron.l e_i|e_j chevron.r = 0
$

#focus-slide[
	Canonical commutator $ [hat(p), hat(x)] = -i planck $
]


== QM --- Uncertanty Principle
#v(20pt)
We define the *uncertainty* of an operator $hat(A)$ in a state $|psi chevron.r$ as its *standard deviation*:
$ 
	Delta^2 hat(A)_psi = chevron.l hat(A)^2 chevron.r_psi - (chevron.l hat(A) chevron.r_psi)^2 = chevron.l (hat(A) - chevron.l hat(A) chevron.r_psi)^2 chevron.r_psi
$

#v(30pt)
#pause
The uncertanty of a pair of operators must satisfy the *uncertainty principle*:
$ 1/4 |chevron.l [hat(A), hat(B)] chevron.r_psi|^2 lt.eq |chevron.l hat(A) hat(B) chevron.r_psi|^2 lt.eq chevron.l hat(A)^2 chevron.r_psi chevron.l hat(B)^2 chevron.r_psi $

#focus-slide[
	Heisemberg's Principle 
	$ Delta^2 hat(x) Delta^2 hat(p) gt.eq planck^2/4 $
]

== QM --- Angular Momentum
#align(center, [
	$ hat(L)_k = (hat(bold(x)) times hat(bold(p)))_k = epsilon_(k i j) hat(x)_i hat(p)_j $

	#pause	
	=== *Commutation rules*
	$
		[hat(L)_i, hat(L)_j] &= i planck epsilon_(i j k) hat(L)_k 
		quad quad
		[hat(L)_i, hat(bold(L))^2] &= 0 
	$ 

	#pause
	#v(5pt)
	=== *Spectrum*
	$ hat(bold(L))^2|l m chevron.r = planck^2 l (l + 1)|l m chevron.r quad l in NN $ 
	#v(5pt)
	$ hat(L)_z|l m chevron.r = planck m|l m chevron.r quad -l lt.eq m lt.eq l $

	#pause
	#v(5pt)
	=== *Degeneracy* $quad d_l = 2l + 1$	
])


// #focus-slide[Theoretical Review]

== QM --- Theoretical Review
#slide[
	#align(horizon + left, figure(image("assets/observed.png", width: 50%)))
][		
	$ hat(bold(mu)) = (planck q_e)/(2 m_e) hat(bold(L))/planck = - g_l mu_B hat(bold(L))/planck $

	#pause  
	#v(20pt)
	$ |psi chevron.r = |l m_l chevron.r $

	#v(10pt)
	$ 
		chevron.l hat(H) chevron.r_psi 
			= - chevron.l hat(mu)_z B_z chevron.r_psi
			= g_l mu_B B_z 1 / planck chevron.l hat(L)_z chevron.r_psi 
	$

	#pause
	#v(10pt)
	But $hat(L)_z$ has $d_l = 2l + 1$ possible eigenvalues, which is *odd*...
	In the case $l = 0$ we should see just one undeflected spot.
]

#focus-slide[=== Why two deflected spots?]


= Spin
== QM --- Intrinsic Angular Momentum
#align(center, [
	#v(10pt)
	=== *Commutation rules*
	#v(10pt)
	$
		[hat(S)_i, hat(S)_j] &= i planck epsilon_(i j k) hat(S)_k 
		quad quad 	
		[hat(S)_i, hat(bold(S))^2] &= 0 
	$ 

	#pause
	#v(10pt)
	=== *Spectrum*
	#v(10pt)
	$hat(bold(S))^2|s m_s chevron.r = planck^2 s (s + 1)|s m_s chevron.r$ 	
	#v(10pt)
	$hat(S)_z|s m_s chevron.r = planck m_s|s m_s chevron.r quad  -s lt.eq m_s lt.eq s$

	#pause
	#v(20pt)
	=== *Degeneracy* $quad d_s = 2s + 1$	
])


== QM --- Theoretical Review
#align(center, [
	#v(15pt)
	$|psi chevron.r = |l m_l chevron.r times.o |s m_s chevron.r quad <-> quad { hat(bold(L))^2, hat(L)_z, hat(bold(S))^2, hat(S)_z } $ 
	
	#pause
	#v(10pt)
	$ hat(bold(mu)) = hat(bold(mu))_l + hat(bold(mu))_s = - mu_B/planck (g_l hat(bold(L)) + g_s hat(bold(S)	)) $

	#pause
	#v(10pt)
	=== *Energy Spectrum*
	#v(5pt)
	$ 
		E_(m_l m_s) &= (mu_B B_z) / planck (g_l chevron.l hat(L)_z chevron.r_psi + g_s chevron.l hat(S)_z chevron.r_psi) \
		pause
		&= mu_B B_z (g_l m_l + g_s m_s)
	$

	#pause
	#v(10pt)
	=== *Degeneracy* $quad d = d_l d_s = (2l + 1)(2s + 1) $	
])



== QM --- Experimental Outcome
#slide[
	#align(left + horizon, figure(image("assets/observed.png", width: 50%)))
][		
	The degeneracy is $quad d = d_s = 2s +1 = 2$
	#pause
	$ s = 1/2  quad => quad m_s &= plus.minus 1/2 $
	#pause
	the SG apparatus is *measuring the spin!*

	#pause
	#v(15pt)
	By measuring the spacing on the screen, from the energy spacing
	$ Delta E_(0, plus.minus 1/2) = g_s mu_B B_z $
	we also conclude that $quad g_s​ = 2$
]

== Conclusion
#v(10pt)
- SG apparatus measures the component of *magnetic momentum* in the field-gradient direction
#pause
#v(15pt)
- To describe the experimental results it was introduced the *spin*, a new degree of freedom with no classical analoguos. 
#pause
#v(15pt)
- Spin can assume both *integer* and *half-integer* eigenvalues.
#pause
#v(15pt)
- Particles are classified by their spin as *bosons* or *fermions*.
#pause
#v(15pt)
- Also *nuclei* and *molecules* have a magnetic momentum. 

== References
#align(center, [
	#v(40pt)
	- #emph[Introduction to the Physics of Matter], Nicola Manini
	#v(20pt)
	- #emph[Fisica quantistica], Stefano Forte, Luca Rottoli
])

#focus-slide[Thank you for the attention!]
#pause

== Total Angular Momentum
#slide[
	Consider a state $|psi chevron.r = |l m_l chevron.r times.o |s m_s chevron.r$

	=== *Definition* 
	$ hat(bold(J)) &= hat(bold(L)) + hat(bold(S)) $
	$ hat(bold(J))^2 = hat(bold(L))^2 + hat(bold(S))^2 + 2 hat(bold(S)) dot hat(bold(L)) $
	
	=== *Commutation rules*
	#v(5pt)
	$ 
		[hat(L)_i, hat(S)_j] = 0  
		quad quad 
		[hat(J)_i, hat(bold(J))^2] = 0 
	$

][
	=== *Spectrum*
	#v(10pt)
	$ hat(bold(J))^2|j m_j chevron.r = planck^2 j (j + 1)|j m_j chevron.r quad |l - s| lt.eq j lt.eq l + s $	
	$ hat(J)_z|j m_j chevron.r = planck m_j|j m_j chevron.r quad  -j lt.eq m_j lt.eq j $

	#v(20pt)
	=== *Degeneracy*
	$ d_j = 2j +  = (2l + 1)(2s + 1) $
]


== Coupling of Angular Momenta
#slide[
	Consider the magnetic field experienced by an $e^-$ orbiting around a nucleus with $Z$ $p^+$
	$ bold(B)(bold(r)) = (Z q_e) / (4 pi epsilon.alt_0 c^2 m_e) hat(bold(L))/(|bold(r)|^3) $

	#v(20pt)
	*Spin-Orbit coupling* $quad hat(H)_(text("s-o")) = - 1/2 hat(bold(mu))_s dot bold(B)$

	$
		hat(H)_(text("s-o")) 	
			&prop 1/r^3 hat(bold(S)) dot hat(bold(L)) \
	
			&prop 1/r^3 (hat(bold(J))^2 - hat(bold(L))^2 - hat(bold(S))^2)
	$
][
 
	We can represent the $e^-$ state using the basis 
	$ { hat(bold(L))^2, hat(L)_z, hat(bold(S))^2, hat(S)_z } $
 	
	Another option is the *coupled* basis 
	$ { hat(bold(J))^2, hat(J)_z, hat(bold(L))^2, hat(bold(S))^2 } $ 
	since
	$
		[hat(J)_z, hat(bold(L))^2] = [hat(J)_z, hat(bold(S))^2] = 0 \
		[hat(bold(J))^2, hat(bold(L))^2] = [hat(bold(J))^2, hat(bold(S))^2] = 0
	$
]



== Energy Spectra in Magnetic Field
#slide[
	#v(20pt)
	=== *Paschen-Back Effect* $quad mu_B B >> xi$
	#v(20pt)
	$ xi_(m_l m_s) = mu_B B_z (m_l + 2 m_s) $

	#v(30pt)
	- Spin-orbit coupling negligible
	- Good quantum numbers: $m_l$, $m_s$
	- Linear splitting
][
	#v(20pt)
	=== *Zeeman Effect* $quad mu_B B << xi$
	#v(20pt)
	$ xi_(m_j) approx.eq g_j m_j mu_B B_z $

	#v(30pt)
	- Spin-orbit coupling dominant
	- $L$ and $S$ coupled to $J$
	- Good quantum numbers: $j$, $m_j$
]