#import "conf.typ": *

#show: bamboo-theme.with(
	title: "Stern-Gerlach Experiment", 
	author: "Luca Cicu - Lorenzo Liuzzo", 
	date: "27/11/2025",
)

#title-slide()

= Experiment description
== Apparatus
#align(
	horizon, 
	figure(
		image("assets/apparatus.png", width: 70%)
	)
)

== Angular & Magnetic momenta
#slide[
	#figure(
		image("assets/angular_magnetic_momentum.png", width: 65%),
		caption: figure.caption(
			position: bottom, 
			[*Angular* and *magnetic* momenta generated by an electron orbiting circularly.]
		)
	)
][
	#pause
	*Angular* momentum $quad bold(L) = bold(x) times bold(p)$

	#v(10pt)		
	*Magnetic* momentum $quad bold(mu) = I Sigma hat(bold(n))$
	#pause
	#v(10pt)
	$ bold(mu) = (q v) / (2 pi r) pi r^2 hat(bold(n)) = q/(2m) bold(L) #pause quad => quad bold(mu) prop bold(L) $

	#pause
	#v(20pt)
	The *interaction* between $bold(mu)$ and an *external magnetic field* $B$ is represented by the magnetic hamitonian
	#v(10pt)
	$ H_(text("magn")) = - bold(mu) dot bold(B) $
]


== Magnetic Interaction
#slide[
	#figure(
		image("assets/force.png", width: 80%),
		caption: [Microscopic origin of the magnetic force.],
		gap: 20pt
	)
][
	#v(10pt)
	$ bold(F)_(text("magn")) = - nabla H_(text("magn")) = nabla(bold(mu) dot bold(B)) $
	
	#pause
	$ F_z = mu_z (partial B_z)/(partial z) #pause = m dot.double(z) $
	
	#pause
	$ z(t) = z_0 + dot(z)_0 t + mu_z/(2 m) (partial B_z)/(partial z) t^2 $
]





= Experimental Results
== Classical Results
#slide[
	#align(horizon + left, figure(image("assets/predicted.png", width: 60%)))
][
	Diocane
]



== Observed Results
#align(horizon + center, figure(image("assets/observed.png", width: 30%)))

#focus-slide[=== Why two deflected spots?]

= Historical Context
== Historical Context
=== Planck quanti 
Hello world 


=== einstein photoe
Hello world 


=== bohr atom
Hello world 

= Quantum Mechanics

== QM --- States
#slide[
	A quantum state is a vector $|psi chevron.r$ in a *Hilbert* space, that is a complete inner product space with normalized elements.
	
	#pause
	- *Basis Properties*
	$ chevron.l e_i|e_j chevron.r = delta_(i j) quad quad I = sum_i |e_i chevron.r chevron.l e_i| $

	#pause
	- *State representation* 
	$ |psi chevron.r = sum_i |e_i chevron.r chevron.l e_i|psi chevron.r = sum_i c_i^psi|e_i chevron.r $
	$c_i^psi = chevron.l e_i|psi chevron.r$ are *probability amplitudes* 
][
	#pause
	- *Inner product* 
	$ chevron.l phi|psi chevron.r = sum_i chevron.l phi|e_i chevron.r chevron.l e_i|psi chevron.r = sum_i (c_i^phi)^* c_i^psi $

	#pause
	- *Born's rule* 
	$ chevron.l psi|psi chevron.r = sum_i (c_i^psi)^* c_i^psi = sum_i |c_i^psi|^2 = 1 $
	$|c_i^psi|^2$ is the *probability* to find $|psi chevron.r$ in $|e_i chevron.r$
]



== QM --- Operators
#v(10pt)
A *linear operator* $hat(O)$ is a transformation from an Hilbert space into itself, that acts like
$ hat(O)(alpha|psi chevron.r + beta|phi chevron.r) = alpha hat(O)|psi chevron.r + beta hat(O)|phi chevron.r = alpha|psi' chevron.r + beta|phi' chevron.r $ 

#v(30pt)
#pause
The action of $hat(O)$ on a state can be entirely represented by its action on some *basis*: 
$ |psi' chevron.r = hat(O)|psi chevron.r = sum_i hat(O)|e_i chevron.r chevron.l e_i|psi chevron.r = sum_(i j) |e_j chevron.r chevron.l e_j|hat(O)|e_i chevron.r chevron.l e_i|psi chevron.r = sum_(i j) |e_j chevron.r O_(i j) c_i^psi $ 

#v(20pt)
#pause
We can also define the *adjoint* operator $hat(O)^dagger$: $quad chevron.l psi'| = chevron.l psi|hat(O)^dagger quad hat(O)^dagger_(i j) = (hat(O)_(j i))^*$



== QM --- Operators & Observables
We can associate every *observable* of a system to an operator
$ 
	hat(O) = sum_i lambda_i|e_i chevron.r chevron.l e_i| 
	quad quad
	hat(O)|e_j chevron.r = sum_i lambda_i|e_i chevron.r chevron.l e_i|e_j chevron.r = lambda_j|e_j chevron.r 
$
#pause
where $lambda_i$ are the *possible results* and $|e_i chevron.r$ are the *possible states* in which the system is founded *after* the measurement. 
#v(10pt)
The requirements are that, *indipendently by the choice of the basis*,  
$ chevron.l e_i|e_j chevron.r = delta_(i j) quad quad lambda_i^* = lambda_i $  

#pause
#v(10pt)
Such operators are called *hermitian* and satisfy 
$quad hat(O)^dagger_(i j) = lambda_i^* delta_(i j) = lambda_i delta_(i j) = hat(O)_(i j)$



== QM --- Commutator of Operators
#v(10pt)
We define the *commutator* between two operators $hat(A)$ and $hat(B)$ as
$ [hat(A), hat(B)] = hat(A) hat(B) - hat(B) hat(A) = - [hat(B), hat(A)] $

#pause
#v(20pt)
$hat(A), hat(B)$ are said to be *compatible iif they commute*, so that $[hat(A), hat(B)] = 0$. 

#pause
#v(30pt)
Two observables can be *simultaneously* determined iif their operators are compatible, \
that is if they share a *common basis* of eigenstates:
$ 
	hat(A)|e_i chevron.r = lambda_i|e_i chevron.r quad 
	hat(B)|e_i chevron.r = mu_i|e_i chevron.r quad <=> quad 
	chevron.l e_i|[hat(A), hat(B)]|e_j chevron.r = (lambda_i mu_i - lambda_j mu_j) chevron.l e_i|e_j chevron.r = 0
$


#focus-slide[
	Position and impulse \ don't commute! $ [hat(p), hat(x)] = -i planck $
]


== QM --- Angular Momentum
#slide[
	=== *Definition*
	#v(5pt)
	$ hat(L)_k = (hat(bold(x)) times hat(bold(p)))_k = epsilon_(k i j) hat(x)_i hat(p)_j $

	#pause	
	#v(10pt)
	=== *Commutation rules*
	#v(10pt)
	$
		[hat(L)_i, hat(L)_j] &= i planck epsilon_(i j k) hat(L)_k 
		quad quad
		[hat(L)_i, hat(bold(L))^2] &= 0 
	$ 

	#pause
	#v(10pt)
	=== *Basis*
	#v(10pt)
	The common eigenstates of $hat(bold(L))^2$ and $hat(L)_z$ are $|l m chevron.r$. 
][
	#v(40pt)
	#pause
	=== *Spectrum*
	#v(10pt)
	$hat(bold(L))^2|l m chevron.r = planck^2 l (l + 1)|l m chevron.r quad l in NN$ 
	#v(10pt)
	$hat(L)_z|l m chevron.r = planck m|l m chevron.r quad -l lt.eq m lt.eq l$

	#pause
	#v(30pt)
	=== *Degeneracy* $quad d_l = 2l + 1$	
]


#focus-slide[Theoretical Review]

== Theoretical Review
#slide[
	#align(horizon + left, figure(image("assets/observed.png", width: 50%)))
][		
	For an electron, $quad hat(bold(mu)) = (planck q_e)/(2 m_e) hat(bold(L))/planck #pause = - g_l mu_B hat(bold(L))/planck$
	#pause
	where $mu_B$ is the *Bohr magneton* and $g_l$ is the *orbital g-factor* (here $g_l = 1$). 

	#pause
	#v(10pt)
	The energy of the system $|psi chevron.r = |l m_l chevron.r$ is
	$ 
		chevron.l hat(H) chevron.r_psi 
			= - chevron.l hat(mu)_z B_z chevron.r_psi
			= g_l mu_B B_z 1 / planck chevron.l hat(L)_z chevron.r_psi 
	$
	$hat(L)_z$ exibits an odd number of discrete eigenvalues ($2l + 1$), so... 
]

#focus-slide[=== Why two deflected spots?]


= Spin
== QM --- Intrinsic Angular Momentum
#slide[
	#v(10pt)
	=== *Commutation rules*
	#v(10pt)
	$
		[hat(S)_i, hat(S)_j] &= i planck epsilon_(i j k) hat(S)_k 
		quad quad 	
		[hat(S)_i, hat(bold(S))^2] &= 0 
	$ 

	#v(10pt)
	=== *Basis*
	The common eigenstates of $hat(bold(S))^2$ and $hat(S)_z$ are $|s m_s chevron.r$. 
][
	=== *Spectrum*
	#v(10pt)
	$hat(bold(S))^2|s m_s chevron.r = planck^2 s (s + 1)|s m_s chevron.r$ 	
	#v(10pt)
	$hat(S)_z|s m_s chevron.r = planck m_s|s m_s chevron.r quad  -s lt.eq m_s lt.eq s$

	#v(20pt)
	=== *Degeneracy* $quad d_s = 2s + 1$	
]


== QM --- Final Theoretical Review
#slide[
	Consider a state $|psi chevron.r = |l m_l chevron.r times.o |s m_s chevron.r$ entering a SG apparatus
	
	#pause
	#v(5pt)
	$ hat(bold(mu)) = hat(bold(mu))_l + hat(bold(mu))_s = - mu_B/planck (g_l hat(bold(L)) + g_s hat(bold(S)	)) $

	#pause
	#v(10pt)
	=== *Basis*
	Since $[hat(L)_i, hat(S)_j] = 0$, we can represent $|psi chevron.r$ using the basis  
	${ hat(bold(L))^2, hat(L)_z, hat(bold(S))^2, hat(S)_z }$
][
	=== *Energy Spectrum*
	$ 
		E_(m_l m_s) &= (mu_B B_z) / planck (g_l chevron.l hat(L)_z chevron.r_psi + g_s chevron.l hat(S)_z chevron.r_psi) \
		&= (mu_B B_z) / planck (g_l m_l + g_s m_s)
	$

	#pause
	=== *Degeneracy* $quad d = (2l + 1)(2s + 1)$	
]



== Final Outcomes
#slide[
	#align(left, figure(image("assets/observed.png", width: 50%)))
][		
	#pause
	$ d_s = 2 quad => quad s = 1/2 quad m_s = plus.minus 1/2 $
	
	#pause
	$ Delta E_(0, plus.minus 1/2) = g_s (mu_B B_z) / planck $

	Also, to make the deflection magnitude match the experiment $g_s​ = 2$
]

#focus-slide[Thank you for the attention!]
#pause

== Total Angular Momentum
#slide[
	Consider a state $|psi chevron.r = |l m_l chevron.r times.o |s m_s chevron.r$

	#pause
	=== *Definition* 
	$ hat(bold(J)) &= hat(bold(L)) + hat(bold(S)) $
	#pause
	$ hat(bold(J))^2 = hat(bold(L))^2 + hat(bold(S))^2 + 2 hat(bold(S)) dot hat(bold(L)) $
	
	#pause
	=== *Commutation rules*
	#v(5pt)
	$ 
		[hat(L)_i, hat(S)_j] = 0  
		quad quad 
		[hat(J)_i, hat(bold(J))^2] = 0 
	$

	#pause
	#v(5pt)
	=== *Basis*
	The common eigenstates of $hat(bold(J))^2$, $hat(J)_z$ are $|j m_j chevron.r$. 

][
	#pause
	=== *Spectrum*
	#v(10pt)
	$ hat(bold(J))^2|j m_j chevron.r = planck^2 j (j + 1)|j m_j chevron.r quad |l - s| lt.eq j lt.eq l + s $	
	$ hat(J)_z|j m_j chevron.r = planck m_j|j m_j chevron.r quad  -j lt.eq m_j lt.eq j $

	#pause
	#v(20pt)
	=== *Degeneracy*
	$ d_j = 2j + 1 #pause = (2l + 1)(2s + 1) $
]


== Coupling of Angular Momenta
#slide[
	Consider the magnetic field experienced by an $e^-$ orbiting around a nucleus with $Z$ $p^+$
	$ bold(B)(bold(r)) = (Z q_e) / (4 pi epsilon.alt_0 c^2 m_e) hat(bold(L))/(|bold(r)|^3) $

	#pause
	#v(20pt)
	*Spin-Orbit coupling* $quad hat(H)_(text("s-o")) = - 1/2 hat(bold(mu))_s dot bold(B)$

	#pause
	$
		hat(H)_(text("s-o")) 	
			&prop 1/r^3 hat(bold(S)) dot hat(bold(L)) \
			#pause
			&prop 1/r^3 (hat(bold(J))^2 - hat(bold(L))^2 - hat(bold(S))^2)
	$
][

	#pause 
	We can represent the $e^-$ state using the basis 
	$ { hat(bold(L))^2, hat(L)_z, hat(bold(S))^2, hat(S)_z } $
 	
	#pause
	Another option is the *coupled* basis 
	$ { hat(bold(J))^2, hat(J)_z, hat(bold(L))^2, hat(bold(S))^2 } $ 
	since
	$
		[hat(J)_z, hat(bold(L))^2] = [hat(J)_z, hat(bold(S))^2] = 0 \
		[hat(bold(J))^2, hat(bold(L))^2] = [hat(bold(J))^2, hat(bold(S))^2] = 0
	$
]



== Energy Spectra in Magnetic Field
	$ 
		hat(H) = hat(H)_0 + hat(H)_(text("s-o")) + (mu_B B_z)/planck (hat(L)_z + 2hat(S)_z)
	$

#slide[
	=== Paschen-Back Effect $quad mu_B B >> xi$
	$ 
		xi_(m_l m_s) &= (mu_B B_z) / planck (chevron.l hat(L)_z chevron.r_psi + 2 chevron.l hat(S)_z chevron.r_psi) \
		&= (mu_B B_z) / planck (m_l + 2 m_s)
	$

	#pause
	=== *Features*
	- Spin-orbit coupling negligible
	- $L$ and $S$ precess independently around $B$
	- Good quantum numbers: $m_l$, $m_s$
	- Linear splitting in $B$

][
	=== Zeeman Effect $quad mu_B B << xi$
	#pause
	=== *Anomalous Zeeman Effect*
	- Spin-orbit coupling dominant
	- $L$ and $S$ coupled to $J$
	- Good quantum numbers: $j$, $m_j$
	- Energy shift: $Delta E = mu_B B g_j m_j$
	
	#pause
	=== *Landé g-factor*
	$
		g_j = 1 + (j(j+1) + s(s+1) - l(l+1))/(2j(j+1))
	$
]



== Boson & Fermions
Hello world

== Conclusion
Hello world