#import "conf.typ": *

#show: bamboo-theme.with(
	title: "Stern-Gerlach Experiment", 
	author: "Luca Cicu - Lorenzo Liuzzo", 
	date: "27/11/2025",
)

#title-slide()

= Historical Context
== Planck quanti 
Hello world 


== einstein photoe
Hello world 


== bohr atom
Hello world 



= Experimental Apparatus

== Angular & Magnetic momenta
#slide[
	#figure(
		image("assets/angular_magnetic_momentum.png", width: 65%),
		caption: figure.caption(
			position: top, 
			[Angular and magnetic momenta generated by an electron orbiting circularly.]
		)
	)
][
	#pause
	$ bold(L) = bold(x) times bold(p) $

	#pause
	#v(10pt)		
	$ 
		bold(mu) 
			= I Sigma hat(bold(n)) #pause
			= (q v) / (2 pi r) pi r^2 hat(bold(n)) #pause 
			= q/(2m) bold(L) 
	$

	#pause
	#v(30pt)
	The *interaction* between an atomic magnetic momentum and an *external magnetic field* is represented by the magnetic hamitonian
	#v(10pt)
	$ H_(text("magn")) = - bold(mu) dot bold(B) $
]


== Apparatus
#slide[][
	#align(
		horizon, 
		figure(
			image("assets/apparatus.png", width: 100%),
			caption: "Stern-Gerlach apparatus."
		)
	)
]

== Magnetic Interaction
#slide[
	#figure(
		image("assets/force.png", width: 80%),
		caption: [Microscopic origin of the magnetic force.],
		gap: 20pt
	)
][
	#v(10pt)
	$ bold(F)_(text("magn")) = - nabla H_(text("magn")) = nabla(bold(mu) dot bold(B)) $
	
	#pause
	$ F_z = mu_z (partial B_z)/(partial z) #pause = m dot.double(z) $
	
	#pause
	$ z(t) = z_0 + dot(z)_0 t + mu_z/(2 m) (partial B_z)/(partial z) t^2 $
]


== Experimental Outcome
#slide[
	#figure(
		image("assets/outcome.png", width: 50%),
		caption: "Stern-Gerlach theoretical versus experimental results."
	)
][	
	#pause
	
	bla bla bla
	#v(60pt)
	
	=== Why do we see two deflected lumps?
]



= Quantum Mechanics

== QM --- States 
The state of a quantum system is a vector in a *Hilbert* space, that is . 
Condizione di ortonormalità: 
$ chevron.l e_i|e_j chevron.r = delta_(i j) $

Relazione di completezza (o risoluzione dell'identità):
$ I = sum_i |e_i chevron.r chevron.l e_i| $

== QM --- States
$ |psi chevron.r = sum_i |e_i chevron.r chevron.l e_i|psi chevron.r = sum_i |e_i chevron.r c_i^psi $


$ chevron.l psi|psi chevron.r = sum_i chevron.l psi|e_i chevron.r chevron.l e_i|psi chevron.r = sum_i (c_i^psi)^* c_i^psi = sum_i |c_i^psi|^2 gt.eq 0 $

$ chevron.l phi|psi chevron.r = sum_i (c_i^phi)^* c_i^psi $



== QM --- Operators
#v(10pt)
A *linear operator* $hat(O)$ is a transformation from an Hilbert space into itself, that acts like
$ hat(O)(alpha|psi chevron.r + beta|phi chevron.r) = alpha hat(O)|psi chevron.r + beta hat(O)|phi chevron.r = alpha|psi' chevron.r + beta|phi' chevron.r $ 

#v(30pt)
#pause
The action of $hat(O)$ on a state can be entirely represented by its action on some *basis*: 
$ |psi' chevron.r = hat(O)|psi chevron.r = sum_i hat(O)|e_i chevron.r chevron.l e_i|psi chevron.r = sum_(i j) |e_j chevron.r chevron.l e_j|hat(O)|e_i chevron.r chevron.l e_i|psi chevron.r = sum_(i j) |e_j chevron.r O_(i j) c_i^psi $ 

#v(20pt)
#pause
We can also define the *adjoint* operator $hat(O)^dagger$: $quad chevron.l psi'| = chevron.l psi|hat(O)^dagger quad hat(O)^dagger_(i j) = (hat(O)_(j i))^*$



== QM --- Operators & Observables
We can associate every *observable* of a system to an operator
$ 
	hat(O) = sum_i lambda_i|e_i chevron.r chevron.l e_i| 
	quad quad
	hat(O)|e_i chevron.r = lambda_i|e_i chevron.r 
$
#pause
where $lambda_i$ are the *possible results* and $|e_i chevron.r$ are the *possible states* in which the system is founded *after* the measurement. 

#pause
#v(10pt)
The requirements are that, *indipendently by the choice of the basis*,  
$ chevron.l e_i|e_j chevron.r = delta_(i j) quad quad lambda_i^* = lambda_i $  

#pause
#v(10pt)
Such operators are called *hermitian* and satisfy 
$quad hat(O)^dagger_(i j) = lambda_i^* delta_(i j) = lambda_i delta_(i j) = hat(O)_(i j)$



== QM --- Commutator of Operators
#v(10pt)
We define the *commutator* between two operators $hat(A)$ and $hat(B)$ as
$ [hat(A), hat(B)] = hat(A) hat(B) - hat(B) hat(A) = - [hat(B), hat(A)] $

#pause
#v(20pt)
$hat(A), hat(B)$ are said to be *compatible iif they commute*, so that $[hat(A), hat(B)] = 0$. 

#pause
#v(30pt)
Two observables can be *simultaneously* determined iif their operators are compatible, \
that is if they share a *common basis* of eigenstates:
$ 
	hat(A)|e_i chevron.r = lambda_i|e_i chevron.r quad 
	hat(B)|e_i chevron.r = mu_i|e_i chevron.r quad <=> quad 
	chevron.l e_i|[hat(A), hat(B)]|e_j chevron.r = (lambda_i mu_i - lambda_j mu_j) chevron.l e_i|e_j chevron.r = 0
$


#focus-slide[
	Position and impulse operators \ don't commute! $ [hat(p), hat(x)] = -i planck $
]


== QM --- Angular Momentum
#slide[
	=== *Definition*
	#v(5pt)
	$ hat(L)_k = (hat(bold(x)) times hat(bold(p)))_k = epsilon_(k i j) hat(x)_i hat(p)_j $

	#pause	
	#v(5pt)
	=== *Commutation rules*
	#v(5pt)
	$
		[hat(L)_i, hat(L)_j] &= i planck epsilon_(i j k) hat(L)_k \
	
		#pause	
		[hat(L)_i, hat(bold(L))^2] &= 0 
	$ 
	since $hat(bold(L))^2$ is a scalar.

	#pause
	For example, we can use $hat(bold(L))^2$ and $hat(L)_z$ to fully determine the angular state of the system.
][
	#pause
	=== *Spectrum*
	#v(5pt)
	The common basis of $hat(bold(L))^2$ and $hat(L)_z$ is $|l m chevron.r$. 
	
	#pause
	#v(5pt)
	$ hat(bold(L))^2|l m chevron.r = planck^2 l (l + 1)|l m chevron.r $ 	
	$ hat(L)_z|l m chevron.r = planck m|l m chevron.r quad  -l lt.eq m lt.eq l $

	#pause
	#v(15pt)
	=== *Degeneracy*
	The number of states with the same $l$ but different $m$, is:	
	$ d_l = 2l + 1 $	
]
  


== Experimental Outcome
#slide[
	#figure(
		image("assets/outcome.png", width: 50%),
		caption: [Stern-Gerlach theoretical versus experimental results.]
	)
][		
	For an electron, $quad hat(bold(mu)) = (planck q_e)/(2 m_e) hat(bold(L))/planck #pause = - g_l mu_B hat(bold(L))/planck$
	where $mu_B$ is the *Bohr magneton* and $g_l$ is the *orbital g-factor* (here $g_l = 1$). 

	#pause
	The energy of the system ...
	$ 
		chevron.l hat(H) chevron.r_psi = - chevron.l B_z hat(mu)_z chevron.r_psi 
		#pause = g_l (mu_B B_z) / planck chevron.l hat(L)_z chevron.r_psi 
	$

	#pause
	For a fixed quantum number $l$, $hat(L)_z$ exibits an odd number of discrete eigenvalues ($2l + 1$). 
	
	#pause
	#align(center, [=== Why do we see *two* deflected lumps?])	
]



= Spin

== QM --- Intrinsic Angular Momentum
#slide[
	=== *Definition*
	#v(5pt)
	$ 
		hat(S)_k = 
	$

	#pause	
	#v(5pt)
	=== *Commutation rules*
	#v(5pt)
	$
		[hat(S)_i, hat(S)_j] &= i planck epsilon_(i j k) hat(S)_k \
	
		#pause	
		[hat(S)_i, hat(bold(S))^2] &= 0 
	$ 
	since $hat(bold(S))^2$ is a scalar.
][
	#pause
	=== *Spectrum*
	#v(5pt)
	The common basis of $hat(bold(S))^2$ and $hat(S)_z$ is $|s m_s chevron.r$. 
	
	#pause
	#v(5pt)
	$ hat(bold(S))^2|s m_s chevron.r = planck^2 s (s + 1)|s m_s chevron.r $ 	
	$ hat(S)_z|s m_s chevron.r = planck m_s|s m_s chevron.r quad  -s lt.eq m_s lt.eq s $

	#pause
	#v(19pt)
	=== *Degeneracy*
	The number of states with the same $s$ but different $m_s$, is:	
	$ d_s = 2s + 1 $	
]



== Experimental Outcome
#slide[
	#figure(
		image("assets/outcome.png", width: 50%),
		caption: [Stern-Gerlach theoretical versus experimental results.]
	)
][		
	=== Why do we see two deflected lumps? *Spin*!
	#v(10pt)
	
	#pause
	$ d_s = 2 = 2 s + 1 quad => quad s = 1/2$
	
	#pause
	$g_s = 2$

]


== Total Angular Momentum
#slide[
	=== *Definition* 
	$ hat(bold(J)) &= hat(bold(L)) + hat(bold(S)) $
	
	#pause
	$ hat(bold(J))^2 = hat(bold(L))^2 + hat(bold(S))^2 + 2 hat(bold(S)) dot hat(bold(L)) $
	
	#pause
	=== *Commutation rules*
	#v(10pt)
	$ 
		[hat(J)_i, hat(J)_j]= i planck epsilon_(i j k) hat(J)_k 
		quad quad 
		[hat(J)_i, hat(bold(J))^2] = 0 
	$

	#pause
	$
		[hat(J)_z, hat(bold(L))^2] = [hat(J)_z, hat(bold(S))^2] = 0
	$
	$
		[hat(bold(J))^2, hat(bold(L))^2] = [hat(bold(J))^2, hat(bold(S))^2] = 0
	$

][
	#pause
	=== *Spectrum*
	#v(5pt)
	The common basis of $hat(bold(J))^2, hat(J)_z, hat(bold(L))^2, hat(bold(S))^2$ is $|j m_j l s chevron.r$. 
	
	#pause
	#v(5pt)
	$ hat(bold(J))^2|j m_j chevron.r = planck^2 j (j + 1)|j m_j chevron.r quad |l - s| lt.eq j lt.eq l + s $	
	$ hat(J)_z|j m_j chevron.r = planck m_j|j m_j chevron.r quad  -j lt.eq m_j lt.eq j $

	#pause
	=== *Degeneracy*
]


== Coupling of Angular Momenta
=== *Spin-Orbit Coupling*
$
	bold(B)(bold(r)) = q_e / (4 pi epsilon.alt_0 c^2 m_e) hat(bold(L))/(|bold(r)|^3)
$
$
	hat(H)_(text("s-o")) 	
		&= - 1/2 hat(bold(mu))_s dot bold(B) \ #pause
		&prop 1/r^3 hat(bold(S)) dot hat(bold(L)) \ #pause
		&prop 1/r^3 (hat(bold(J))^2 - hat(bold(L))^2 - hat(bold(S))^2)
$

#pause
We can choose which basis to use to represent 


== Total Magnetic Momentum
$ hat(bold(mu)) = hat(bold(mu))_l + hat(bold(mu))_s = - mu_B/planck (g_l hat(bold(L)) + g_s hat(bold(S))) $

$ |psi chevron.r = |l m_l chevron.r times.o |s m_s chevron.r $

$ 
	xi_(m_l m_s) &= (mu_B B_z) / planck (chevron.l hat(L)_z chevron.r_psi + 2 chevron.l hat(S)_z chevron.r_psi) \
	&= (mu_B B_z) / planck (m_l + 2 m_s)
$


== Energy Spectra in Magnetic Field
#slide[
	=== Paschen-Back Limit $quad mu_B B >> xi$
	Hello world 

][
	=== Zeeman Limit $quad mu_B B << xi$
	Hello world
]

== Boson & Fermions
Hello world

== Conclusion
Hello world