#import "conf.typ": *

#show: bamboo-theme.with(
	aspect-ratio: "16-9",
	title: self => self.info.title,	
	footer: self => self.info.author,
	config-info(
		title: "Stern-Gerlach Experiment", 
		author: "Luca Cicu - Lorenzo Liuzzo", 
		date: "27/11/2025",
	),
)


#title-slide()

= Historical Context ( slides)
== Planck quanti 
Dicoan 

== einstein photoe
diocan 

== bohr atom


= Experimental Apparatus ( slides)


== Angular & Magnetic momenta
#grid(
	columns: 2,
	gutter: 50pt,
	[
		#align(
			figure(
				image("assets/angular_magnetic_momentum.png", width: 60%),
				caption: [Angular and magnetic momentum \ generated by an electron orbiting circularly.]
			)
		)
	],
	[
		#pause
		$ bold(L) = bold(x) times bold(p) $
		#pause
		#v(10pt)		
		$ bold(mu) &= I Sigma hat(bold(n)) #pause
					= (q v) / (2 pi r) pi r^2 hat(bold(n)) #pause \ &= q/(2m) bold(L) $
	]
)


== Apparatus
#slide[][
	#align(
		horizon, 
		figure(
			image("assets/apparatus.png", width: 100%),
			caption: "Stern-Gerlach apparatus."
		)
	)
]

== Magnetic Interaction
#slide[
	#align(
		horizon,
		[
			The *interaction* between an atomic magnetic momentum with an *external magnetic field* is governed by 
			#v(20pt)
			$ H = - bold(mu) dot bold(B) $
					
			#v(10pt)
			$ 
				bold(F) = - nabla H = nabla(bold(mu) dot bold(B)) \
				=> F_z = mu_z (partial B_z)/(partial z)
			$

		]
	)		
][
	#align(
		horizon + center, 
		figure(
			image("assets/force.png", width: 100%),
			caption: [Origin of the **magnetic force**.],
			gap: 20pt
		)
	)
]

== Experimental Outcome
#slide[
	#align(
		horizon + right, 
		figure(
			image("assets/outcome.png", width: 50%),
			caption: "Stern-Gerlach theoretical versus experimental results."
		)
	)	
][	
	#pause
	
	bla bla bla
	#v(60pt)
	
	=== Why do we see two deflected lumps?
]


= Quantum Mechanics ( slides)

== QM --- States 
The state of a quantum system is a vector in a *Hilbert* space, that is . 
Condizione di ortonormalità: 
$ chevron.l e_i|e_j chevron.r = delta_(i j) $

Relazione di completezza (o risoluzione dell'identità):
$ I = sum_i |e_i chevron.r chevron.l e_i| $

== QM --- States
$ |psi chevron.r = sum_i |e_i chevron.r chevron.l e_i|psi chevron.r = sum_i |e_i chevron.r c_i^psi $


$ chevron.l psi|psi chevron.r = sum_i chevron.l psi|e_i chevron.r chevron.l e_i|psi chevron.r = sum_i (c_i^psi)^* c_i^psi = sum_i |c_i^psi|^2 gt.eq 0 $

$ chevron.l phi|psi chevron.r = sum_i (c_i^phi)^* c_i^psi $


== QM --- Operators
#v(10pt)
A *linear operator* $hat(O)$ is a transformation from an Hilbert space into itself, that acts like
$ hat(O)(alpha|psi chevron.r + beta|phi chevron.r) = alpha hat(O)|psi chevron.r + beta hat(O)|phi chevron.r = alpha|psi' chevron.r + beta|phi' chevron.r $ 

#v(30pt)
#pause
The action of $hat(O)$ on a state can be entirely represented by its action on some *basis*: 
$ |psi' chevron.r = hat(O)|psi chevron.r = sum_i hat(O)|e_i chevron.r chevron.l e_i|psi chevron.r = sum_(i j) |e_j chevron.r chevron.l e_j|hat(O)|e_i chevron.r chevron.l e_i|psi chevron.r = sum_(i j) |e_j chevron.r O_(i j) c_i^psi $ 

#v(20pt)
#pause
We can also define the *adjoint* operator $hat(O)^dagger$: $quad chevron.l psi'| = chevron.l psi|hat(O)^dagger quad hat(O)^dagger_(i j) = (hat(O)_(j i))^*$


== QM --- Operators & Observables

We can associate every *observable* of a system to an operator
$ 
	hat(O) = sum_i lambda_i|e_i chevron.r chevron.l e_i| 
	quad quad
	hat(O)|e_i chevron.r = lambda_i|e_i chevron.r 
$
where: 
- $|e_i chevron.r$ are the *possible states* in which the system is *after* the measurement 
- $lambda_i$ are the *results* of the measurement

#pause
The *requirements* are, indipendently by the choice of the basis $quad chevron.l e_i|e_j chevron.r = delta_(i j) quad lambda_i^* = lambda_i$  


#pause
Such operators are called *hermitian* and satisfy 
$quad hat(O)^dagger_(i j) = lambda_i^* delta_(i j) = lambda_i delta_(i j) = hat(O)_(i j)$


== QM --- Commutator of Operators
#v(10pt)
#pause
Given two operators $hat(A)$ and $hat(B)$, we define their *commutator* as
$ [hat(A), hat(B)] = hat(A) hat(B) - hat(B) hat(A) = - [hat(B), hat(A)] $

#pause
$hat(A), hat(B)$ are said to be *compatible iif they commute*, so that $[hat(A), hat(B)] = 0$. 

#v(30pt)
#pause
Two different observables are *simultaneously determined* iif compatible,
that is if they share a *common basis* of eigenstates:
$ 
	hat(A)|e_i chevron.r = lambda_i|e_i chevron.r quad 
	hat(B)|e_i chevron.r = mu_i|e_i chevron.r quad <=> quad 
	chevron.l e_i|[hat(A), hat(B)]|e_j chevron.r = (lambda_i mu_i - lambda_j mu_j) chevron.l e_i|e_j chevron.r = 0
$

#focus-slide[
	Position and impulse operators \ don't commute! $ [hat(p), hat(x)] = -i planck $
]


== QM --- Angular Momentum
#stack( 
	$ hat(L)_k = (hat(bold(x)) times hat(bold(p)))_k = epsilon_(k i j) hat(x)_i hat(p)_j $,

	align(center + horizon, 
		grid(
			columns: 2,
			gutter: 30pt,
			align(horizon, [
				#pause	
				=== *Commutation rules*
				#v(10pt)
				$ [hat(L)_i, hat(L)_j] = i planck epsilon_(i j k) hat(L)_k $
				$ [hat(bold(L))^2, hat(L)_i] = 0 $
			]),
			align(horizon, [
				#pause
				=== *Quantization*				
				#v(5pt)
				$ hat(L)_z |l m chevron.r = planck m |l m chevron.r $
				$ hat(bold(L))^2 |l m chevron.r = planck^2 l (l + 1) |l m chevron.r $ 		
				$ -l lt.eq m_l lt.eq l quad => quad d_l = 2l + 1 $	
			])
		)
	)
)  

== QM --- Magnetic Momentum
For an electron, we can generally write
$ hat(bold(mu)) = (planck q_e)/(2 m_e) hat(bold(L))/planck = - g_l mu_B hat(bold(L))/planck $
where $mu_B$ is the *Bohr magneton*  
and $g_l$ is the *orbital g-factor* (here $g_l = 1$). 


== Experimental Outcome
#slide[
	#align(
		horizon + right, 
		figure(
			image("assets/outcome.png", width: 50%),
			caption: "Stern-Gerlach theoretical versus experimental results."
		)
	)	
][		
	=== Why do we see *two* deflected lumps?
	#v(10pt)
	
	#pause
	$hat(L)_z$ exibits an odd number of discrete eigenvalues ($2l + 1$). 
	
	#pause
	Even if we try with the GS of H ($l = 0$), we should see just one lump.

]


= Spin

== Intrinsic Angular Momentum
#stack(
	v(20pt), 
	$ hat(S)_k = 
	 $,
	v(50pt), 

	align(center + horizon, 
		grid(
			columns: 2,
			gutter: 30pt,
			align(horizon, [
				#pause	
				=== *Commutation rules*
				#v(10pt)
				$ [hat(S)_i, hat(S)_j] = i planck epsilon_(i j k) hat(S)_k $
				$ [hat(bold(S))^2, hat(S)_i] = 0 $
			
			]),
			align(horizon, [
				#pause
				=== *Quantization*				
				#v(5pt)
				$ hat(S)_z |s m_s chevron.r = planck m_s |s m_s chevron.r $
				$ hat(bold(S))^2 |s m_s chevron.r = planck^2 s (s + 1) |s m_s chevron.r $ 
				$ -s lt.eq m_s lt.eq s quad => quad d_s = 2s + 1$
			])
		)
	)
)  

== Experimental Outcome
#slide[
	#align(
		horizon + right, 
		figure(
			image("assets/outcome.png", width: 50%),
			caption: "Stern-Gerlach theoretical versus experimental results."
		)
	)	
][		
	=== Why do we see two deflected lumps? *Spin*!
	#v(10pt)
	
	#pause
	$ d_s = 2 = 2 s + 1 quad => quad s = 1/2$
	
	#pause
	$g_s = 2$

]


== Total Magnetic Momentum
$ bold(mu) = bold(mu)_l + bold(mu)_s = - mu_B/planck (g_l bold(L) + g_s bold(S)) $

$ |psi chevron.r = |l m_l chevron.r times.o |s m_s chevron.r $

$ E = chevron.l hat(H) chevron.r_psi = - chevron.l hat(mu)_z chevron.r_psi = -  $

== Energy Spectra in Magnetic Field
diocan 

=== Paschen-Back Limit $mu_B B >> E$
diocan 

=== Zeeman Limit $mu_B B << E$
diocan

== Conclusion
diocan 
